const key = {
    "A": [
        [5,null,null,null,null,null],
        [null,0,null,null,null,null],
        [null,12,null,null,null,null],
        [null,null,7,null,null,null],
        [null,null,null,2,null,null],
        [null,null,null,null,10,null],
        [null,null,null,null,null,5],
    ],
    "A#/Bb": [
        [6,null,null,null,null,null],
        [null,1,null,null,null,null],
        [null,null,8,null,null,null],
        [null,null,null,3,null,null],
        [null,null,null,null,11,null],
        [null,null,null,null,null,6],
    ],
    "B": [
        [7,null,null,null,null,null],
        [null,2,null,null,null,null],
        [null,null,9,null,null,null],
        [null,null,null,4,null,null],
        [null,null,null,null,0,null],
        [null,null,null,null,12,null],
        [null,null,null,null,null,7],
    ],
    "C": [
        [8,null,null,null,null,null],
        [null,3,null,null,null,null],
        [null,null,10,null,null,null],
        [null,null,null,5,null,null],
        [null,null,null,null,1,null],
        [null,null,null,null,null,8],
    ],
    "C#/Db": [
        [9,null,null,null,null,null],
        [null,4,null,null,null,null],
        [null,null,11,null,null,null],
        [null,null,null,6,null,null],
        [null,null,null,null,2,null],
        [null,null,null,null,null,9],
    ],
    "D": [
        [10,null,null,null,null,null],
        [null,5,null,null,null,null],
        [null,null,0,null,null,null],
        [null,null,12,null,null,null],
        [null,null,null,7,null,null],
        [null,null,null,null,3,null],
        [null,null,null,null,null,10],
    ],
    "D#/Eb": [
        [11,null,null,null,null,null],
        [null,6,null,null,null,null],
        [null,null,1,null,null,null],
        [null,null,null,8,null,null],
        [null,null,null,null,4,null],
        [null,null,null,null,null,11],
    ],
    "E": [
        [0,null,null,null,null,null],
        [12,null,null,null,null,null],
        [null,7,null,null,null,null],
        [null,null,2,null,null,null],
        [null,null,null,9,null,null],
        [null,null,null,null,5,null],
        [null,null,null,null,null,0],
        [null,null,null,null,null,12],
    ],
    "F": [
        [1,null,null,null,null,null],
        [null,8,null,null,null,null],
        [null,null,3,null,null,null],
        [null,null,null,10,null,null],
        [null,null,null,null,6,null],
        [null,null,null,null,null,1],
    ],
    "F#/Gb": [
        [2,null,null,null,null,null],
        [null,9,null,null,null,null],
        [null,null,4,null,null,null],
        [null,null,null,11,null,null],
        [null,null,null,null,7,null],
        [null,null,null,null,null,2],
    ],
    "G": [
        [3,null,null,null,null,null],
        [null,10,null,null,null,null],
        [null,null,5,null,null,null],
        [null,null,null,0,null,null],
        [null,null,null,12,null,null],
        [null,null,null,null,8,null],
        [null,null,null,null,null,3],
    ],
    "G#/Ab": [
        [4,null,null,null,null,null],
        [null,11,null,null,null,null],
        [null,null,6,null,null,null],
        [null,null,null,1,null,null],
        [null,null,null,null,9,null],
        [null,null,null,null,null,4],
    ]
}

export default key